version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: monthly
  ignore:
    - dependency-name: "node"
      update-types: ["version-update:semver-major"]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
