/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.3/userguide/building_swift_projects.html in the Gradle documentation.
 */

plugins {
  id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "wiremock-http4k"

createProject("src/app", ":app")
createProject("src/email", ":email")
createProject("src/http4k-ext", ":http4k-ext")
createProject("src/wiremock-ext", ":wiremock-ext")
createProject("src/wiremock-http4k", ":wiremock-http4k")

fun Settings.createProject(projectDir: String, projectName: String) {
  include(projectName)
  project(projectName).projectDir = projectDir.toFile()
}

fun String.toFile() = File(this)
