/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wiremock.http4k.app

import org.apache.commons.text.WordUtils
import wiremock.http4k.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
