/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wiremock.http4k.kotlin-library-conventions")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
}
