/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("wiremock.http4k.kotlin-application-conventions")
}

application {
  // Define the main class for the application.
  mainClass.set("wiremock.http4k.app.AppKt")
}
