/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0")
    implementation("org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin:3.16.0")
    implementation("com.dorongold.task-tree:com.dorongold.task-tree.gradle.plugin:2.1.1")
    implementation("com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.47.0")
}
